FROM node:latest

RUN apt-get update    && apt-get install -y nginx

WORKDIR /app

COPY package.json ./

RUN yarn install

COPY . .

RUN yarn build

RUN cp -r dist/* /var/www/html 

EXPOSE 80


CMD ["nginx","-g","daemon off;"]





