name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: change folder
        uses: docker/build-push-action@v2
        working-directory: nuxt/network-v
        run: ls
      - name: docker build
        with:
          push: true
          tags: abdoubentegar/sdn-react
      # - name: docker-build
      #   uses: docker/build-push-action@v2
      #   working-directory: nuxt/network-v
      #   with:
      #     push: true
      #     tags: user/app:latest