from ubuntu 


RUN  apt-get update 
RUN    apt-get install -y --no-install-recommends python-setuptools  python-pip  python-eventlet  python-lxml  wget  unzip
RUN      apt-get clean 
RUN     rm -rf /var/lib/apt/lists/* 
RUN     echo "Download https://github.com/osrg/ryu/archive/master.zip and install" 
RUN     wget -O /opt/ryu.zip "http://github.com/osrg/ryu/archive/master.zip" --no-check-certificate 
RUN      unzip -q /opt/ryu.zip -d /opt 
RUN     mv /opt/ryu-master /opt/ryu &&     
RUN  /opt/ryu.zip 
RUN      cd /opt/ryu 
RUN     pip install -r tools/pip-requires &&     python ./setup.py install


RUN   pip install -r /opt/ryu/tools/pip-requires --upgrade

EXPOSE 6633/tcp

RUN mkdir /app

WORKDIR /opt/ryu 

WORKDIR /app

COPY ./ .

 CMD ["./bin/ryu-manager" "./load_balance.py ../rest_topology.py --observe-links"]



