from ubuntu 


RUN  apt-get update 
RUN    apt-get install -y --no-install-recommends python-setuptools    python3-eventlet  python3-lxml  wget  unzip
RUN apt-get install -y python pip

RUN   pip install ryu

EXPOSE 6633/tcp


RUN mkdir /app


WORKDIR /app

COPY ./ .

WORKDIR /app
RUN ls /usr/local/bin

CMD ["/usr/local/bin/ryu  " ,"run ./load_balance.py ../rest_topology.py --observe-links"]



