name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: should it be skipped?
        env:
          COMMIT_FILTER: "build-react"
        run: | 
          # Get last commit message
          readonly local last_commit_log=$(git log -1 --pretty=format:"%s")
          echo "last commit log: $last_commit_log"

          readonly local filter_count=$(echo "$last_commit_log" | grep -c "$COMMIT_FILTER" )
          echo "number of occurence of '$COMMIT_FILTER' in '$last_commit_log': $filter_count"

          if [[ "$filter_count" eq 0 ]]; then
            echo "all good, continue" 
          else
            echo "the last commit log \"$last_commit_log\" contains \"$COMMIT_FILTER\", stopping"
            exit 78
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: abdoubentegar/sdn-react,abdoubentegar/sdn-react:0.2
          file: nuxt/network-v/dockerfile
          context: ./nuxt/network-v
